import Head from 'next/head';
import Navbar from '../components/Navbar';
import Main from '../components/Main';
import About from '../components/About';
import Image from 'next/image';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Mine|portfiolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Main/>
      <About/>
     

     
    </div>
  )
}
